openapi: 3.1.0
info:
  title: Knownwell api-keys documentation API
  description: API for accessing Knownwell client data and Knownwell scores
  version: v1
tags:
- name: documentation
paths:
  /docs:
    get:
      tags:
      - documentation
      summary: Documentation
      description: Serve custom API documentation.
      operationId: documentation_docs_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
components:
  securitySchemes:
    APIKeyHeader:
      type: apiKey
      in: header
      name: X-API-Key
